// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
)

type Cart struct {
	ID         string
	TotalPrice float64
	UserID     string
	CreatedAt  string
	UpdatedAt  string
}

type CartProduct struct {
	CartID          string
	ProductID       string
	ProductName     string
	ProductPrice    float64
	ProductDiscount float64
	Quantity        int64
	FinalPrice      float64
}

type Category struct {
	ID          string
	Name        string
	Description string
}

type Order struct {
	ID            string
	NetPrice      float64
	TotalPrice    float64
	PaymentMethod string
	Status        string
	UserID        string
	CreatedAt     string
	UpdatedAt     string
}

type OrderProduct struct {
	OrderID         string
	ProductID       string
	ProductName     string
	ProductPrice    float64
	ProductDiscount float64
	Quantity        int64
	FinalPrice      float64
}

type Product struct {
	ID          string
	Name        string
	Description string
	Brand       string
	ByRequest   int64
	Discount    float64
	Price       float64
	Stock       int64
	Issued      int64
	Images      string
	CategoryID  string
	CreatedAt   string
	UpdatedAt   string
	DeletedAt   sql.NullString
}

type ProductRating struct {
	Rating    int64
	ProductID string
	UserID    string
}

type Session struct {
	ID           string
	RefreshToken string
	AccessToken  string
	Username     string
	UserID       string
	Device       string
	CreatedAt    string
}

type User struct {
	ID          string
	FirstName   string
	LastName    string
	Alias       string
	Username    string
	Email       string
	Password    string
	PhoneNumber string
	BirthDate   string
	Role        string
	CreatedAt   string
	UpdatedAt   string
	DeletedAt   sql.NullString
}
